// Auto-generated by sync.mjs — do not edit by hand.
// Source: Coda doc dJMxdg1mRFk. Run `node sync.mjs` to regenerate.
// Generated 2026-05-27T17:48:51.056Z
window.DATA = {
  "trip": {
    "title": "Japan & Korea 2026",
    "start": "2026-07-22",
    "end": "2026-08-05"
  },
  "days": [],
  "activities": [],
  "todos": [
    {
      "id": "i-OwODpLyzhJ",
      "priority": "Critical```",
      "item": "```Changdeokgung Secret Garden```",
      "type": "```Tickets```",
      "day": "```Aug 2```",
      "whenToBook": "```NOW```",
      "link": "https://eng.cdg.go.kr/",
      "why": "```Secret Garden requires advance reservation and fills up fast, especially in summer```",
      "rec": "```Book immediately — limited daily entry slots```"
    },
    {
      "id": "i-cQT8XGUQN3",
      "priority": "Critical```",
      "item": "```Hakone Kowakien Ten-yu kaiseki dinner```",
      "type": "```Restaurant```",
      "day": "```July 29```",
      "whenToBook": "```At time of hotel booking```",
      "link": "https://www.ten-yu.com/en/",
      "why": "```Kaiseki dinner at the ryokan is typically pre-arranged as part of your stay package — confirm it's included when you book```",
      "rec": "```Confirm dinner is included in your room plan or add it at booking```"
    },
    {
      "id": "i-MZjRXTuRdb",
      "priority": "Important```",
      "item": "```RURU SHIBUYA```",
      "type": "```Restaurant```",
      "day": "```July 24```",
      "whenToBook": "```Walk-in only, no reservations```",
      "link": "https://maps.app.goo.gl/TosocKzN5RqZwAiQ6",
      "why": "```Only ~15 seats, closes at 8 PM. Queues form quickly on weekends```",
      "rec": "```Arrive close to 11 AM right after teamLab to avoid long waits```"
    },
    {
      "id": "i-IwAhfALqhZ",
      "priority": "Important```",
      "item": "```Onitsuka Tiger Shinjuku South```",
      "type": "```Shopping```",
      "day": "```July 26```",
      "whenToBook": "```Walk-in, no reservation needed```",
      "link": "https://www.onitsukatiger.com/jp/ja-jp",
      "why": "```Can get busy but notably less crowded than Omotesando. Best to go on a weekday or early.```",
      "rec": "```Go early afternoon before evening food tour```"
    },
    {
      "id": "i-nwUmpjokEx",
      "priority": "Important```",
      "item": "```KUOE KYOTO Omotesando```",
      "type": "```Shopping```",
      "day": "```July 25```",
      "whenToBook": "```Walk-in, no reservation needed```",
      "link": "https://linktr.ee/kuoe_kyoto",
      "why": "```Small boutique, closes at 5:30 PM. Closed Tuesdays. July 25 is Saturday so you're fine.```",
      "rec": "```Go before 5:30 PM during Omotesando wandering```"
    },
    {
      "id": "i-W_C8yst36C",
      "priority": "Important```",
      "item": "```Mt. Fuji 5th Station — Fuji Subaru Line road fee```",
      "type": "```Logistics```",
      "day": "```July 31```",
      "whenToBook": "```Pay on the day at the toll gate```",
      "link": "https://www.fujisan-climb.jp/en/",
      "why": "```The Fuji Subaru Line charges a vehicle fee (around 2,000 yen) at the gate. Just have cash or card ready.```",
      "rec": "```No advance booking needed — just pay at the gate on the way```"
    },
    {
      "id": "i-y3MqrmrDLY",
      "priority": "Helpful```",
      "item": "```Coin lockers at Fuji 5th Station for backpacks```",
      "type": "```Logistics```",
      "day": "```July 31```",
      "whenToBook": "```No advance booking```",
      "link": "",
      "why": "```Standard travel backpacks (40–50L) should fit. Have 100-yen coins ready.```",
      "rec": "```Use lockers so you can walk around freely at the summit```"
    },
    {
      "id": "i-heGjfgzEjj",
      "priority": "Helpful```",
      "item": "```Download Google Maps offline — Tokyo, Hakone, Seoul```",
      "type": "```Travel Setup```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "```Google Maps app```",
      "why": "```Japan mobile data is reliable but offline maps are a lifesaver in transit tunnels and rural areas```",
      "rec": "```Download all three regions before you leave home```"
    },
    {
      "id": "i-asKBXXQhie",
      "priority": "Helpful```",
      "item": "```Download Hyperdia or Google Maps for Japan transit```",
      "type": "```Travel Setup```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "https://www.hyperdia.com/en/",
      "why": "```Essential for navigating JR and subway connections```",
      "rec": "```Google Maps works well in Japan for transit — just make sure it's updated```"
    },
    {
      "id": "i-1FlwtfNSVI",
      "priority": "Critical```",
      "item": "```Watch ticktok on mobile app.```",
      "type": "",
      "day": "",
      "whenToBook": "",
      "link": "",
      "why": "",
      "rec": ""
    },
    {
      "id": "i-k2u_F6LU9-",
      "priority": "Critical```",
      "item": "```Register for visit Japan.com```",
      "type": "",
      "day": "",
      "whenToBook": "",
      "link": "",
      "why": "",
      "rec": ""
    },
    {
      "id": "i-R7G7LTEut-",
      "priority": "Critical```",
      "item": "```teamLab Planets TOKYO```",
      "type": "```Tickets```",
      "day": "```July 24```",
      "whenToBook": "```NOW```",
      "link": "https://www.teamlab.art/e/planets/",
      "why": "```Summer slots sell out quickly```",
      "rec": "```Book ASAP```"
    },
    {
      "id": "i-F6Jtonjv7E",
      "priority": "Critical```",
      "item": "```Shibuya Sky```",
      "type": "```Tickets```",
      "day": "```July 24```",
      "whenToBook": "```NOW```",
      "link": "https://www.shibuya-scramble-square.com/sky/",
      "why": "```Sunset/night slots are hardest to get```",
      "rec": "```Prioritize this reservation```"
    },
    {
      "id": "i-V522RR3Cen",
      "priority": "Critical```",
      "item": "```Sumo Stable Practice```",
      "type": "```Tour```",
      "day": "```July 28```",
      "whenToBook": "```NOW```",
      "link": "https://www.getyourguide.com/",
      "why": "```Hardest experience to secure```",
      "rec": "```Book immediately```"
    },
    {
      "id": "i-V7LcbkANHf",
      "priority": "Critical```",
      "item": "```DMZ / JSA Tour```",
      "type": "```Tour```",
      "day": "```Aug 1```",
      "whenToBook": "```NOW```",
      "link": "https://www.getyourguide.com/",
      "why": "```Access changes often```",
      "rec": "```Book highly rated operator```"
    },
    {
      "id": "i-xRmg-qixSD",
      "priority": "Critical```",
      "item": "```Shinjuku night food tour```",
      "type": "```Tour```",
      "day": "```July 26```",
      "whenToBook": "```Next few weeks```",
      "link": "https://www.getyourguide.com/",
      "why": "```Great recovery-day guided experience```",
      "rec": "```Probably your best “insider Tokyo” night```"
    },
    {
      "id": "i-IbEydHNeUF",
      "priority": "Critical```",
      "item": "```Asakusa guided food/culture tour```",
      "type": "```Tour```",
      "day": "```July 27```",
      "whenToBook": "```Next few weeks```",
      "link": "https://www.getyourguide.com/",
      "why": "```Adds huge value to traditional Tokyo```",
      "rec": "```Small-group local guide recommended```"
    },
    {
      "id": "i-dLTH6crVhh",
      "priority": "Critical```",
      "item": "```Sumida River Fireworks Festival viewing strategy```",
      "type": "```Event Planning```",
      "day": "```July 25```",
      "whenToBook": "```NOW```",
      "link": "```https://www.klook.com/ OR https://www.getyourguide.com/```",
      "why": "```Crowds and heat are intense```",
      "rec": "```Consider reserved seating/rooftop```"
    },
    {
      "id": "i-9QxksNLX_z",
      "priority": "Critical```",
      "item": "```Romancecar / Hakone train seats```",
      "type": "```Transit```",
      "day": "```July 29```",
      "whenToBook": "```2–4 weeks before```",
      "link": "https://www.odakyu.jp/english/romancecar/",
      "why": "```Summer seats fill```",
      "rec": "```Reserve family seats together```"
    },
    {
      "id": "i-rhvQdn_7VG",
      "priority": "Important```",
      "item": "```Kura Sushi```",
      "type": "```Restaurant```",
      "day": "```July 26```",
      "whenToBook": "```Morning of or day before```",
      "link": "https://www.kurasushi.co.jp/en/",
      "why": "```Evening waits can get long```",
      "rec": "```Use app or online queue```"
    },
    {
      "id": "i-4NRnsh2daH",
      "priority": "Important```",
      "item": "```FLIPPER'S Shibuya```",
      "type": "```Restaurant```",
      "day": "```July 24```",
      "whenToBook": "```1–2 weeks before```",
      "link": "https://flipper-s.com/",
      "why": "```Morning lines can get long```",
      "rec": "```Reserve if possible```"
    },
    {
      "id": "i-83vb_oI2OP",
      "priority": "Important```",
      "item": "```Pepper PARLOR```",
      "type": "```Restaurant```",
      "day": "```July 24```",
      "whenToBook": "```1–2 weeks before```",
      "link": "https://www.pepperparlor.com/",
      "why": "```Helps keep Shibuya day smooth```",
      "rec": "```Nice-to-have reservation```"
    },
    {
      "id": "i-vNFvdMIxMi",
      "priority": "Important```",
      "item": "```Hedgehog Café HARRY```",
      "type": "```Activity```",
      "day": "```July 25```",
      "whenToBook": "```1–2 weeks before```",
      "link": "https://www.harinezumi-cafe.com/english",
      "why": "```Small capacity```",
      "rec": "```Reserve if convenient```"
    },
    {
      "id": "i-tzUW1RKhDX",
      "priority": "Important```",
      "item": "```Airport limo/private transfer (optional)```",
      "type": "```Transit```",
      "day": "```July 23```",
      "whenToBook": "```1–2 weeks before```",
      "link": "https://webservice.limousinebus.co.jp/web/en/",
      "why": "```Easier after long flight```",
      "rec": "```Optional comfort upgrade```"
    },
    {
      "id": "i-XddZPB8IzE",
      "priority": "Helpful```",
      "item": "```eSIM / Pocket WiFi```",
      "type": "```Travel setup```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "```https://www.airalo.com/ OR https://www.ubigi.com/```",
      "why": "```Essential for navigation/transit```",
      "rec": "```eSIM easiest for family```"
    },
    {
      "id": "i-NwiHq1cJ3v",
      "priority": "Helpful```",
      "item": "```Suica / IC cards setup```",
      "type": "```Transit```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure or airport```",
      "link": "```Apple Wallet / JR East app```",
      "why": "```Makes trains effortless```",
      "rec": "```Add to Apple Wallet```"
    },
    {
      "id": "i-bh_Yduvs5j",
      "priority": "Helpful```",
      "item": "```Portable battery packs```",
      "type": "```Packing```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "```Amazon / Best Buy```",
      "why": "```Phones drain fast in Tokyo heat```",
      "rec": "```Ideally one per person```"
    },
    {
      "id": "i-w6Evl9gxcP",
      "priority": "Helpful```",
      "item": "```Cooling towels / neck fans```",
      "type": "```Packing```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "```Amazon```",
      "why": "```Huge comfort upgrade```",
      "rec": "```Especially for fireworks```"
    },
    {
      "id": "i-YiXVjH4XqX",
      "priority": "Helpful```",
      "item": "```UV umbrella/parasol```",
      "type": "```Packing```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure or buy in Japan```",
      "link": "```Amazon / Don Quijote```",
      "why": "```Makes July heat much easier```",
      "rec": "```You’ll see locals using them everywhere```"
    }
  ],
  "flights": [
    {
      "trip": "```Tokyo → Seoul```",
      "airline": "```Korean Air```",
      "number": "```Korean ```2708```",
      "from": "```HND```",
      "to": "```ICN```",
      "fromCity": "```Tokyo (Haneda)```",
      "toCity": "```Seoul (Incheon)```",
      "date": "",
      "depart": "",
      "arrive": ""
    },
    {
      "trip": "```Seattle → Tokyo```",
      "airline": "```Alaska Airlines```",
      "number": "```Alaska ```823```",
      "from": "```SEA```",
      "to": "```NRT```",
      "fromCity": "```Seattle```",
      "toCity": "```Tokyo (Narita)```",
      "date": "",
      "depart": "",
      "arrive": ""
    },
    {
      "trip": "```Seoul → Seattle```",
      "airline": "```Alaska Airlines```",
      "number": "```Alaska ```172```",
      "from": "```ICN```",
      "to": "```SEA```",
      "fromCity": "```Seoul (Incheon)```",
      "toCity": "```Seattle```",
      "date": "",
      "depart": "",
      "arrive": ""
    }
  ]
};
(function(){
  const D = window.DATA;
  D.byId = {}; D.activities.forEach(a => D.byId[a.id] = a);
  D.byDay = {}; D.days.forEach(d => D.byDay[d.n] = d);
  D.dayActivities = {}; D.activities.forEach(a => {
    (D.dayActivities[a.day] = D.dayActivities[a.day] || []).push(a);
  });
})();
