// Auto-generated by sync.mjs — do not edit by hand.
// Source: Coda doc dJMxdg1mRFk. Run `node sync.mjs` to regenerate.
// Generated 2026-05-27T18:51:10.401Z
window.DATA = {
  "trip": {
    "title": "Japan & Korea 2026",
    "start": "2026-07-22",
    "end": "2026-08-05"
  },
  "days": [
    {
      "n": 1,
      "date": "2026-07-22",
      "title": "```Day 1: Flight to Japan```",
      "loc": "Travel",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 47.4502,
      "lng": -122.3088,
      "color": "#5c6f87",
      "overview": "```Day 1: Flight to Japan```",
      "notes": "```Cross dateline; arrive July 23. Flight AS 823 departs Seattle 1:30 PM. In-flight meals provided — no planning needed.```",
      "hero": "```https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 2,
      "date": "2026-07-23",
      "title": "```Day 2: Tokyo Arrival```",
      "loc": "",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 35.6896,
      "lng": 139.6995,
      "color": "#1e6a9a",
      "overview": "```Day 2: Tokyo Arrival```",
      "notes": "```Keep first night intentionally light for jet lag recovery. Narita Express to Shinjuku takes ~90 mins. MIMARU is a short walk from Shinjuku Station. Kabukicho and convenience stores are open late — perfect for a low-key first night.```",
      "hero": "```https://images.unsplash.com/photo-1554797589-7241bb691973?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 3,
      "date": "2026-07-24",
      "title": "```Day 3: Modern Tokyo & Shibuya```",
      "loc": "",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 35.658,
      "lng": 139.7016,
      "color": "#8e44ad",
      "overview": "```Day 3: Modern Tokyo & Shibuya```",
      "notes": "```Reserve teamLab Planets and Shibuya Sky in advance — both sell out, especially summer weekends. RURU SHIBUYA has no reservations; arrive close to 11 AM opening to avoid long waits — closes 8 PM. teamLab is in Toyosu (requires transit). Shibuya Sky best at sunset — book 6–6:45 PM slot.```",
      "hero": "```https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 4,
      "date": "2026-07-25",
      "title": "```Day 4: Harajuku & Fireworks```",
      "loc": "",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 35.6702,
      "lng": 139.7027,
      "color": "#c0392b",
      "overview": "```Day 4: Harajuku & Fireworks```",
      "notes": "```All outdoor activities front-loaded in the morning before peak heat. Shinjuku Gyoen open 9 AM (closed Mondays — July 25 is Saturday, fine). Do Meiji Shrine and Yoyogi Park walk-through before 10 AM. Move into air-conditioned Harajuku shops by late morning. Afternoon is indoors — Purikura, KUOE (closes 5:30 PM), Omotesando boutiques. Hotel recharge essential before fireworks. Bring cooling towels and water for the evening — fireworks crowds are intense and hot. Arrive at viewing area by 4–5 PM. Fireworks begin ~7 PM. Wear comfortable shoes.```",
      "hero": "```https://images.unsplash.com/photo-1528164344705-47542687000d?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 5,
      "date": "2026-07-26",
      "title": "```Day 5: Shinjuku Nightlife```",
      "loc": "",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 35.6938,
      "lng": 139.7036,
      "color": "#b25a14",
      "overview": "```Day 5: Shinjuku Nightlife```",
      "notes": "```Sleep in — recovery day after fireworks. Onitsuka Tiger Shinjuku South is less crowded than Omotesando but still gets busy — go early afternoon. Bic Camera and Yodobashi Camera open at 10 AM. Night food tour typically runs 5:30–7:30 PM — book in advance. Kura Sushi: use their app or online queue to avoid waits. Keep evening flexible for spontaneous discoveries after the tour.```",
      "hero": "```https://images.unsplash.com/photo-1554797589-7241bb691973?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 6,
      "date": "2026-07-27",
      "title": "```Day 6: Traditional Tokyo```",
      "loc": "",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 35.7148,
      "lng": 139.7967,
      "color": "#0e7560",
      "overview": "```Day 6: Traditional Tokyo```",
      "notes": "```All outdoor Asakusa activities front-loaded — aim to finish Senso-ji and Nakamise by noon before peak heat. Tsukiji vendors sell out by midday so early start is essential anyway. Akihabara in the afternoon is entirely air-conditioned — perfect heat refuge during the hottest hours (noon–3 PM). Super Potato opens 11 AM. Gachapon closes ~8 PM. Relaxed pacing — recovery day after fireworks night.```",
      "hero": "```https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 7,
      "date": "2026-07-28",
      "title": "```Day 7: Sumo & Shimokitazawa```",
      "loc": "",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 35.6614,
      "lng": 139.6677,
      "color": "#1e7d42",
      "overview": "```Day 7: Sumo & Shimokitazawa```",
      "notes": "```Sumo stable practice very early — typically 6–9 AM, indoors. Afternoon: head straight to indoor spots — Village Vanguard and cafés are air-conditioned and ideal during peak heat (noon–3 PM). Outdoor wandering, vintage shops, and record stores best after 5 PM when temperature drops. Village Vanguard open until 11 PM. Flexible day — let Ann choose if plans change. Pack for Hakone tonight.```",
      "hero": "```https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 8,
      "date": "2026-07-29",
      "title": "```Day 8: Tokyo to Hakone```",
      "loc": "",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 35.2324,
      "lng": 139.026,
      "color": "#2c3e50",
      "overview": "```Day 8: Tokyo to Hakone```",
      "notes": "```You're travelling on backpacks so luggage forwarding is not needed. Romancecar departs from Shinjuku Station — reserve seats in advance, especially for families. Aim to check in to Ten-yu by 4 PM. Kaiseki dinner is at 7:30 PM — confirm inclusion at time of hotel booking.```",
      "hero": "```https://images.unsplash.com/photo-1480796927426-f609979314bd?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 9,
      "date": "2026-07-30",
      "title": "```Day 9: Relaxed Hakone Day```",
      "loc": "",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 35.2324,
      "lng": 139.026,
      "color": "#6c3483",
      "overview": "```Day 9: Relaxed Hakone Day```",
      "notes": "```Weather-optimized order: outdoor lakeside activities in the morning while cooler, then ropeway and Owakudani in the afternoon — both are at elevation (~1000m) and noticeably cooler than the valley. Open-Air Museum has shaded indoor sections and closes at 5 PM — do it last before returning to the ryokan. Back by 4–5 PM for onsen during peak late-afternoon heat. Ropeway can have long summer queues — go earlier in the afternoon. Owakudani may be closed if volcanic activity is elevated — check on arrival. Tea House check hours on arrival.```",
      "hero": "```https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 10,
      "date": "2026-07-31",
      "title": "```Day 10: Hakone to Korea```",
      "loc": "Travel",
      "country": "JP",
      "flag": "🇯🇵",
      "lat": 35.3956,
      "lng": 138.7325,
      "color": "#3a6ea5",
      "overview": "```Day 10: Hakone to Korea```",
      "notes": "```Depart Hakone by 11 AM to fit in Mt. Fuji 5th Station stop. Fuji Subaru Line has a vehicle road fee — pay at the gate. Coin lockers at 5th Station for backpacks — bring 100-yen coins. Drive Hakone → Fuji 5th Station ~1.5 hrs, 1 hr at top, ~2.5 hrs to Haneda. Flight to Seoul departs HND 8:15 PM — arrive airport by 6 PM.```",
      "hero": "```https://images.unsplash.com/photo-1578637387939-43c525550085?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 11,
      "date": "2026-08-01",
      "title": "```Day 11: DMZ Adventure```",
      "loc": "",
      "country": "KR",
      "flag": "🇰🇷",
      "lat": 37.9586,
      "lng": 126.6779,
      "color": "#c0392b",
      "overview": "```Day 11: DMZ Adventure```",
      "notes": "```Bring passports — required for JSA entry. Book DMZ/JSA tour well in advance through a reputable operator. Full day — typically departs Seoul 7–8 AM. JSA access can be restricted on short notice due to political situations. Long day on your feet. Itaewon Korean BBQ in the evening is a well-earned reward.```",
      "hero": "```https://images.unsplash.com/photo-1538485399081-7191377e8241?w=900&h=600&auto=format&fit=crop&crop=top&q=70```"
    },
    {
      "n": 12,
      "date": "2026-08-02",
      "title": "```Day 12: Palaces & Museums```",
      "loc": "",
      "country": "KR",
      "flag": "🇰🇷",
      "lat": 37.5794,
      "lng": 126.991,
      "color": "#b53124",
      "overview": "```Day 12: Palaces & Museums```",
      "notes": "```Secret Garden requires advance reservation — limited daily slots, book immediately. Changdeokgung Palace opens at 9 AM. Bukchon Hanok Village is best in the morning before tour groups arrive — also be respectful as people live there. National Museum of Korea is free entry and closed Tuesdays — Aug 2 is Sunday, fine. Gwangjang Market is best in the evening for the full atmosphere.```",
      "hero": "```https://images.unsplash.com/photo-1538485399081-7191377e8241?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 13,
      "date": "2026-08-03",
      "title": "```Day 13: Fish Market & Sky Views```",
      "loc": "",
      "country": "KR",
      "flag": "🇰🇷",
      "lat": 37.5128,
      "lng": 126.9408,
      "color": "#922b21",
      "overview": "```Day 13: Fish Market & Sky Views```",
      "notes": "```Noryangjin Fish Market is best very early (6–8 AM) for the freshest selection and auction atmosphere. COEX Mall and Starfield Library open at 10 AM. Dongdaemun Design Plaza is free to visit the exterior 24/7; interior exhibition hours vary. Seoul Sky (Lotte World Tower) — book tickets in advance for sunset slot. Gangnam dinner — area is lively but pricier than other Seoul neighborhoods.```",
      "hero": "```https://images.unsplash.com/photo-1538669715315-155098f0fb1d?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 14,
      "date": "2026-08-04",
      "title": "```Day 14: Markets & Hongdae```",
      "loc": "",
      "country": "KR",
      "flag": "🇰🇷",
      "lat": 37.5563,
      "lng": 126.9237,
      "color": "#a93226",
      "overview": "```Day 14: Markets & Hongdae```",
      "notes": "```Namdaemun Market opens early and is best before noon. N Seoul Tower accessible by cable car or walk up Namsan Park — cable car can have queues. Namsan Park is pleasant in the evening with city views. Hongdae is most vibrant after 8 PM — great farewell night. Last full day for souvenir shopping.```",
      "hero": "```https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=900&auto=format&fit=crop&q=70```"
    },
    {
      "n": 15,
      "date": "2026-08-05",
      "title": "```Day 15: Journey Home```",
      "loc": "Travel",
      "country": "KR",
      "flag": "🇰🇷",
      "lat": 37.4602,
      "lng": 126.4407,
      "color": "#7b241c",
      "overview": "```Day 15: Journey Home```",
      "notes": "```Flight AS 172 departs ICN 7:35 PM — arrive Incheon Airport by 4:30 PM (allow 3+ hours). Incheon has excellent shopping and food in the terminal — arrive early and enjoy. Check luggage weight limits for the return — Japanese and Korean shopping adds up fast.```",
      "hero": "```https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=900&auto=format&fit=crop&q=70```"
    }
  ],
  "activities": [
    {
      "id": "i-aXPH49l4nG",
      "day": 1,
      "time": "",
      "name": "```Poop pants```",
      "desc": "```crap them pants```",
      "url": "```poopy.com```",
      "cat": "",
      "lat": null,
      "lng": null
    },
    {
      "id": "i-6vGpGL9b96",
      "day": 10,
      "time": "",
      "name": "```Mt. Fuji 5th Station```",
      "desc": "```A spectacular detour on the way from Hakone to Haneda Airport. The Fuji Subaru Line climbs to 2,305 meters on the north side of Mt. Fuji, where the 5th Station offers sweeping views of the surrounding landscape, often above the cloud line. On a clear day the views are jaw-dropping and the air is noticeably cooler and crisper than at sea level. There are gift shops, restaurants, and a small shrine. Coin lockers are available for storing backpacks while you walk around. Allow about 1.5 hours driving from Hakone, 1 hour at the top, then 2.5 hours to Haneda — leave Hakone by 11 AM to be comfortable for an 8:15 PM flight. Note: the Fuji Subaru Line road has a seasonal vehicle fee.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.fujisan-climb.jp/en/"
      },
      "cat": "",
      "lat": 35.3956,
      "lng": 138.7325
    },
    {
      "id": "i-ZjwuWxqHYx",
      "day": 3,
      "time": "",
      "name": "```Tokyu Hands Shibuya```",
      "desc": "```A legendary multi-floor department store packed with gadgets, stationery, craft supplies, travel gear, beauty products, and all manner of bizarre and useful Japanese novelty items. Every floor has something unexpected and it's a great place to pick up gifts and souvenirs. Open until 9 PM, conveniently located right next to PARCO in Shibuya.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://shibuya.hands.net/"
      },
      "cat": "",
      "lat": 35.6608,
      "lng": 139.6982
    },
    {
      "id": "i-gZPqox2KKD",
      "day": 4,
      "time": "",
      "name": "```Shinjuku Gyoen```",
      "desc": "```One of Tokyo's most beautiful national gardens, combining Japanese, French, and English garden styles across 58 hectares. A rare peaceful escape from the energy of Shinjuku, with wide lawns, manicured tree-lined paths, tranquil ponds, and a beautiful greenhouse. Closed Mondays. Open 9 AM–6 PM. Free for under-18s.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.env.go.jp/garden/shinjukugyoen/english/index.html"
      },
      "cat": "",
      "lat": 35.6852,
      "lng": 139.71
    },
    {
      "id": "i-0LHtpvMsdJ",
      "day": 5,
      "time": "",
      "name": "```Bic Camera Shinjuku```",
      "desc": "```A massive multi-floor electronics megastore in East Shinjuku with an attached Uniqlo. Covers cameras, phones, gaming, watches, appliances, toys, anime figures, and more. Great for Japanese tech souvenirs at competitive prices with tax-free shopping. Easy to lose an hour in.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.biccamera.com/bc/tenpo/BCT0018/index.jsp"
      },
      "cat": "",
      "lat": 35.6907,
      "lng": 139.7038
    },
    {
      "id": "i-8TIxleQllM",
      "day": 6,
      "time": "",
      "name": "```Super Potato Akihabara```",
      "desc": "```The most famous retro video game store in Japan and a pilgrimage site for any gaming fan. Spread across multiple floors of vintage consoles, cartridges, and gaming memorabilia spanning every era from Famicom to PlayStation. The top floor has a working retro arcade where you can actually play classic machines. An absolute must for the boys.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.superpotato.com/"
      },
      "cat": "",
      "lat": 35.7008,
      "lng": 139.771
    },
    {
      "id": "i-VYtjLlVvzX",
      "day": 6,
      "time": "",
      "name": "```Yodobashi Akihabara```",
      "desc": "```One of the largest electronics retail complexes in the world, with eight interconnected floors covering cameras, gaming, audio, drones, watches, toys, hobby supplies, and a full floor of anime figures and collectibles. Tax-free shopping available. Right at the entrance to Akihabara station.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.yodobashi-akiba.com/"
      },
      "cat": "",
      "lat": 35.7019,
      "lng": 139.7749
    },
    {
      "id": "i-tQcq9on3LL",
      "day": 7,
      "time": "",
      "name": "```Village Vanguard Shimokitazawa```",
      "desc": "```A wonderfully chaotic pop-culture store crammed with books, manga, band merchandise, novelty items, weird snacks, quirky toys, and Japanese oddities. Equal parts bookstore and curiosity shop, it captures the offbeat spirit of Shimokitazawa perfectly. Great for picking up gifts and finding things you never knew existed.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.village-v.co.jp/"
      },
      "cat": "",
      "lat": 35.6614,
      "lng": 139.668
    },
    {
      "id": "i-iMrm2_OrHC",
      "day": 3,
      "time": "",
      "name": "```RURU SHIBUYA```",
      "desc": "```A uniquely atmospheric café tucked on the 2nd floor of Shibuya Sakura Stage, famous for its stunning \"water table\" concept where desserts and drinks appear to float above a bed of pebbles in a shallow pool. Known for matcha lattes, black sesame cheesecake, and signature mousse desserts. Very small space — only around 15 seats — so arrive early or expect a queue. One drink and one food item minimum per person, one-hour seating limit. A little hard to find: take the escalator up and turn left. Closes at 8 PM so aim to visit earlier in the afternoon, ideally right after teamLab Planets.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://maps.app.goo.gl/TosocKzN5RqZwAiQ6"
      },
      "cat": "",
      "lat": 35.6575,
      "lng": 139.7
    },
    {
      "id": "i-_-3Pi0IfLo",
      "day": 4,
      "time": "",
      "name": "```Yoyogi Park```",
      "desc": "```A vast, forested park just a short walk from Harajuku and Meiji Shrine. On weekends it comes alive with street performers, musicians, cosplayers, picnickers, and a generally festive atmosphere. A great spot to decompress between Meiji Shrine and Takeshita Street, or just wander under the trees. Free to enter and open all day.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/spot/35/index.html"
      },
      "cat": "",
      "lat": 35.672,
      "lng": 139.6948
    },
    {
      "id": "i-OhY3sfiTgf",
      "day": 4,
      "time": "",
      "name": "```Purikura Photo Booth```",
      "desc": "```A quintessentially Japanese experience — Purikura are photo booths that take groups of photos and then let you decorate them with stickers, stamps, digital backgrounds, and cute filters before printing wallet-sized strips to keep. Found in arcades throughout Harajuku and Shibuya, they're a fun and cheap souvenir. Look for them in Shibuya's Purikura no Mecca or any game center.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.google.com/search?q=Purikura+photo+booth+Shibuya+Harajuku"
      },
      "cat": "",
      "lat": 35.671,
      "lng": 139.704
    },
    {
      "id": "i-LU2WXccA-x",
      "day": 4,
      "time": "",
      "name": "```KUOE KYOTO Omotesando```",
      "desc": "```A boutique watch brand originally from Kyoto, now with a Tokyo outpost right on Omotesando boulevard. KUOE makes beautifully crafted Japanese watches with interchangeable straps and a distinct artisan aesthetic. The Tokyo store carries exclusive colorways not available in Kyoto and is much less crowded than the original. Staff speak excellent English and offer a relaxed, personalized experience. Open 11 AM–5:30 PM; closed Tuesdays.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://linktr.ee/kuoe_kyoto"
      },
      "cat": "",
      "lat": 35.6662,
      "lng": 139.7124
    },
    {
      "id": "i-hQfacRLoxX",
      "day": 4,
      "time": "",
      "name": "```Onitsuka Tiger Omotesando```",
      "desc": "```The flagship Onitsuka Tiger store in Tokyo, located right on Omotesando boulevard. Carries the widest selection of styles in the city and is consistently the most popular location — expect queues, especially on weekends. The trick is to ask staff for your size and style, take a seat, and wait for them to bring the shoes to you. Prices are roughly half of US retail, and tax-free shopping is available with your passport. Arrive as close to 11 AM as possible to beat the afternoon crowds.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.onitsukatiger.com/jp/ja-jp"
      },
      "cat": "",
      "lat": 35.6883,
      "lng": 139.7016
    },
    {
      "id": "i-Tgbsi29qjT",
      "day": 6,
      "time": "",
      "name": "```Asakusa Viral Street Food```",
      "desc": "```The narrow lanes surrounding Nakamise Shopping Street and Senso-ji are packed with vendors selling some of Tokyo's most iconic and social-media-famous street snacks. Look for freshly grilled ningyo-yaki (fish- and bell-shaped red bean cakes), thick rolled tamagoyaki (sweet egg omelette on a stick), melon pan straight from the oven, strawberry daifuku, and crispy senbei rice crackers made to order. The crowds and aromas are part of the experience — arrive hungry and graze your way toward the temple.\n\n- Ningyo-yaki — red bean cakes molded into charming Asakusa-themed shapes, grilled fresh in iron molds\n- Tamagoyaki — thick sweet rolled egg omelette on a stick, a Tsukiji and Asakusa staple\n- Melon pan — soft, sweet bread with a crispy sugar crust, best eaten warm right from the bakery\n- Strawberry daifuku — mochi filled with fresh whole strawberry and sweet cream\n- Agemanju — deep-fried steamed buns with sweet red bean filling, crispy outside and pillowy inside\n- Senbei — freshly grilled rice crackers made to order, brushed with soy sauce over an open flame```",
      "url": "",
      "cat": "",
      "lat": 35.714,
      "lng": 139.7965
    },
    {
      "id": "i-lrv4IIsiIR",
      "day": 1,
      "time": "",
      "name": "```Alaska/Hawaiian Flight to Tokyo```",
      "desc": "```Begin your transpacific journey to Japan with an overnight international flight crossing the International Date Line.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.alaskaair.com/"
      },
      "cat": "",
      "lat": 47.4502,
      "lng": -122.3088
    },
    {
      "id": "i-re_ngHfBWS",
      "day": 2,
      "time": "",
      "name": "```Arrive Narita Airport```",
      "desc": "```Land in Japan and experience your first taste of Tokyo energy at Narita Airport.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.narita-airport.jp/en/"
      },
      "cat": "",
      "lat": 35.772,
      "lng": 140.3929
    },
    {
      "id": "i-9kRwfKyBbi",
      "day": 2,
      "time": "",
      "name": "```Narita Express to Shinjuku```",
      "desc": "```Ride Japan’s famously efficient Narita Express into central Tokyo.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.jreast.co.jp/multi/en/nex/"
      },
      "cat": "",
      "lat": 35.6896,
      "lng": 139.7006
    },
    {
      "id": "i-n-P40d4FSl",
      "day": 2,
      "time": "",
      "name": "```Kabukicho Walk```",
      "desc": "```Wander through glowing neon streets, arcades, tiny bars, and bustling entertainment alleys in Shinjuku’s iconic nightlife district.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/destinations/western-tokyo/shinjuku/index.html"
      },
      "cat": "",
      "lat": 35.6948,
      "lng": 139.7029
    },
    {
      "id": "i-32BTP_fDqH",
      "day": 2,
      "time": "",
      "name": "```First Ramen Dinner```",
      "desc": "```Your first authentic Tokyo ramen experience after arriving in Japan.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/tokyo/restaurants/best-ramen-in-shinjuku"
      },
      "cat": "",
      "lat": 35.6938,
      "lng": 139.7036
    },
    {
      "id": "i-2qZ9Di2qQx",
      "day": 2,
      "time": "",
      "name": "```Convenience Store Snack Run```",
      "desc": "```Explore Japanese convenience stores filled with incredible snacks, desserts, drinks, and bizarre seasonal treats.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://livejapan.com/en/article-a0000688/"
      },
      "cat": "",
      "lat": 35.6936,
      "lng": 139.702
    },
    {
      "id": "i-Jz8vj-6614",
      "day": 3,
      "time": "",
      "name": "```FLIPPER’S Soufflé Pancakes```",
      "desc": "```Start the morning with Tokyo’s famous fluffy soufflé pancakes.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://flippers-pancake.jp/"
      },
      "cat": "",
      "lat": 35.6595,
      "lng": 139.6993
    },
    {
      "id": "i-JVeWTHnEQ8",
      "day": 3,
      "time": "",
      "name": "```teamLab Planets TOKYO```",
      "desc": "```Step barefoot into one of the world’s most immersive digital art museums where entire rooms react to your movement with light, water, sound, and projection mapping. Wander through floating flower gardens, mirrored infinity spaces, glowing digital waterfalls, and knee-deep water installations that blur the line between art, technology, and physical space. This is one of Tokyo’s signature modern experiences and consistently one of the most memorable highlights for first-time visitors.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.teamlab.art/e/planets/"
      },
      "cat": "",
      "lat": 35.6537,
      "lng": 139.7892
    },
    {
      "id": "i-Orql9IYLzk",
      "day": 3,
      "time": "",
      "name": "```Pepper PARLOR```",
      "desc": "```Futuristic robot café experience with interactive robot servers and playful technology-driven dining.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.pepperparlor.com/"
      },
      "cat": "",
      "lat": 35.6583,
      "lng": 139.7032
    },
    {
      "id": "i-ruIk0cdX3P",
      "day": 3,
      "time": "",
      "name": "```Nintendo TOKYO```",
      "desc": "```Explore Nintendo’s flagship Tokyo store filled with exclusive merchandise, gaming displays, and themed collectibles.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.nintendo.com/jp/topics/article/2db1f009-fc3d-48dc-a58d-0f0c8e8a6b40"
      },
      "cat": "",
      "lat": 35.6594,
      "lng": 139.7008
    },
    {
      "id": "i-Ierm_-B8R-",
      "day": 3,
      "time": "",
      "name": "```PARCO Shopping```",
      "desc": "```Explore Tokyo’s trendiest shopping complex filled with gaming, anime, fashion, and pop culture stores.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://shibuya.parco.jp.e.aiv.hp.transer.com/"
      },
      "cat": "",
      "lat": 35.6611,
      "lng": 139.6986
    },
    {
      "id": "i-GUL18oPGCO",
      "day": 3,
      "time": "",
      "name": "```Shibuya Crossing```",
      "desc": "```Experience the world’s most famous pedestrian crossing amid Tokyo’s dazzling neon skyline.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/spot/59/index.html"
      },
      "cat": "",
      "lat": 35.6595,
      "lng": 139.7005
    },
    {
      "id": "i-_WgQ0dE0Q9",
      "day": 3,
      "time": "",
      "name": "```Giant Parfait Café```",
      "desc": "```Enjoy absurdly over-the-top Japanese dessert creations towering with fruit, cream, and ice cream.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/tokyo/restaurants/best-parfaits-in-tokyo"
      },
      "cat": "",
      "lat": 35.6608,
      "lng": 139.7019
    },
    {
      "id": "i-y5Zhd8OOYN",
      "day": 3,
      "time": "",
      "name": "```Shibuya Sky```",
      "desc": "```Soar above Tokyo atop one of the city’s most spectacular observation decks suspended high above Shibuya Crossing. The open-air rooftop offers breathtaking 360-degree views stretching across Tokyo’s endless skyline toward Tokyo Tower, Tokyo Skytree, and even Mount Fuji on clear evenings. Visiting during sunset is especially magical as the city slowly transforms from golden-hour glow into a vast ocean of neon lights.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.shibuya-scramble-square.com/sky/"
      },
      "cat": "",
      "lat": 35.6586,
      "lng": 139.7028
    },
    {
      "id": "i-b-IRRhfhMn",
      "day": 3,
      "time": "",
      "name": "```Shibuya Wandering```",
      "desc": "```Explore side streets, neon alleys, music shops, arcades, and hidden cafés around Shibuya.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/destinations/western-tokyo/shibuya/index.html"
      },
      "cat": "",
      "lat": 35.662,
      "lng": 139.6995
    },
    {
      "id": "i-mJIgvrk7Wq",
      "day": 4,
      "time": "",
      "name": "```Meiji Shrine```",
      "desc": "```Hidden within a massive forest in the center of Tokyo, Meiji Shrine feels worlds away from the city’s neon energy. Massive torii gates, shaded gravel pathways, towering cedar trees, and peaceful shrine buildings create one of Tokyo’s most calming and atmospheric cultural experiences. Dedicated to Emperor Meiji and Empress Shoken, the shrine beautifully blends Shinto tradition with nature and is especially wonderful in the cooler morning hours.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.meijijingu.or.jp/en/"
      },
      "cat": "",
      "lat": 35.6764,
      "lng": 139.6993
    },
    {
      "id": "i-jqZ8KuRY8u",
      "day": 4,
      "time": "",
      "name": "```Harajuku Exploration```",
      "desc": "```Wander through Tokyo’s colorful youth-fashion district filled with quirky shops and pop culture energy.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/destinations/western-tokyo/harajuku/index.html"
      },
      "cat": "",
      "lat": 35.6702,
      "lng": 139.7027
    },
    {
      "id": "i-qs0WepQIh1",
      "day": 4,
      "time": "",
      "name": "```Takeshita Street```",
      "desc": "```Dive into Harajuku’s iconic street lined with crepe stands, candy shops, and playful fashion boutiques.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/spot/41/index.html"
      },
      "cat": "",
      "lat": 35.6716,
      "lng": 139.7028
    },
    {
      "id": "i-fS88CRUT6x",
      "day": 4,
      "time": "",
      "name": "```Hedgehog Café HARRY```",
      "desc": "```Relax at one of Tokyo’s whimsical animal cafés featuring adorable hedgehogs.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.harinezumi-cafe.com/english"
      },
      "cat": "",
      "lat": 35.6712,
      "lng": 139.703
    },
    {
      "id": "i-FtRPI0JIP_",
      "day": 4,
      "time": "",
      "name": "```Harajuku Street Snacks & Crepes```",
      "desc": "```Sample iconic Japanese crepes and trendy street snacks while wandering Harajuku.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/tokyo/restaurants/best-crepes-in-harajuku"
      },
      "cat": "",
      "lat": 35.6705,
      "lng": 139.7032
    },
    {
      "id": "i-IyCmMmYS82",
      "day": 4,
      "time": "",
      "name": "```Omotesando Wandering```",
      "desc": "```Explore stylish tree-lined boulevards filled with luxury architecture and hidden cafés.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/destinations/western-tokyo/omotesando/index.html"
      },
      "cat": "",
      "lat": 35.666,
      "lng": 139.7126
    },
    {
      "id": "i-IJ-dYPBVEf",
      "day": 4,
      "time": "",
      "name": "```Hotel Recharge Break```",
      "desc": "```Return to the hotel for showers, rest, and AC before fireworks crowds.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 35.6909,
      "lng": 139.695
    },
    {
      "id": "i-zgez79OhcK",
      "day": 4,
      "time": "",
      "name": "```Sumida River Fireworks Festival```",
      "desc": "```One of Japan’s oldest and most famous fireworks festivals, the Sumida River Fireworks Festival transforms Tokyo into an unforgettable summer celebration filled with yukata, food stalls, riverside crowds, and spectacular fireworks displays. Tens of thousands of fireworks erupt over the Sumida River while the Tokyo skyline glows in the background, creating one of the most iconic summer experiences in all of Japan. The atmosphere is energetic, crowded, festive, and absolutely unforgettable.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://en.japantravel.com/tokyo/sumidagawa-fireworks-festival/24685"
      },
      "cat": "",
      "lat": 35.7106,
      "lng": 139.8003
    },
    {
      "id": "i-9h2Kg1XIlR",
      "day": 5,
      "time": "",
      "name": "```Sleep In & Relaxed Brunch```",
      "desc": "```Slow recovery morning after fireworks night.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 35.6909,
      "lng": 139.695
    },
    {
      "id": "i-JBLckUFDMS",
      "day": 5,
      "time": "",
      "name": "```Isetan Shinjuku Depachika```",
      "desc": "```Graze through one of Tokyo’s most legendary basement food halls featuring incredible desserts, sushi, wagyu, and pastries.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.mistore.jp/store/shinjuku.html"
      },
      "cat": "",
      "lat": 35.6918,
      "lng": 139.7044
    },
    {
      "id": "i-0f0ig4MGiw",
      "day": 5,
      "time": "",
      "name": "```Yodobashi Camera Shinjuku```",
      "desc": "```Explore towering electronics megastores filled with gadgets, cameras, toys, gaming gear, and tech.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.yodobashi.com/ec/store/0018/"
      },
      "cat": "",
      "lat": 35.692,
      "lng": 139.6985
    },
    {
      "id": "i-8VO7I4hSzY",
      "day": 5,
      "time": "",
      "name": "```Guided Shinjuku Night Food Tour```",
      "desc": "```Explore hidden alleys, yakitori bars, lantern-lit streets, and local eateries with a guide.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.getyourguide.com/tokyo-l193/tokyo-shinjuku-food-tour-t190779/"
      },
      "cat": "",
      "lat": 35.694,
      "lng": 139.7032
    },
    {
      "id": "i-J1i-hxAYbg",
      "day": 5,
      "time": "",
      "name": "```Kura Sushi Dinner```",
      "desc": "```Enjoy conveyor-belt sushi with touchscreen ordering and prize games perfect for families.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.kurasushi.co.jp/en/"
      },
      "cat": "",
      "lat": 35.6939,
      "lng": 139.7045
    },
    {
      "id": "i-Xr_dsqkpZO",
      "day": 5,
      "time": "",
      "name": "```Omoide Yokocho (Piss Alley)```",
      "desc": "```Wander atmospheric lantern-lit alleyways packed with tiny yakitori bars and smoky food stalls.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/spot/44/index.html"
      },
      "cat": "",
      "lat": 35.6929,
      "lng": 139.6998
    },
    {
      "id": "i-jut0l5gzTY",
      "day": 5,
      "time": "",
      "name": "```Golden Gai```",
      "desc": "```Explore Tokyo’s iconic maze of miniature bars and nightlife alleys.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/spot/63/index.html"
      },
      "cat": "",
      "lat": 35.6939,
      "lng": 139.7041
    },
    {
      "id": "i-i-CtvsMHPT",
      "day": 5,
      "time": "",
      "name": "```Shinjuku Batting Center```",
      "desc": "```Experience classic Japanese urban batting cages glowing beneath neon lights.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/tokyo/things-to-do/shinjuku-batting-center"
      },
      "cat": "",
      "lat": 35.6947,
      "lng": 139.7053
    },
    {
      "id": "i-0Fj-eR5QBT",
      "day": 5,
      "time": "",
      "name": "```Retro Arcades```",
      "desc": "```Dive into nostalgic Japanese gaming culture with multi-floor retro arcades.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/tokyo/things-to-do/best-game-centres-in-tokyo"
      },
      "cat": "",
      "lat": 35.6938,
      "lng": 139.705
    },
    {
      "id": "i-nNfuyJL49r",
      "day": 5,
      "time": "",
      "name": "```Don Quijote```",
      "desc": "```Explore Tokyo’s chaotic late-night discount megastore packed with bizarre Japanese products and souvenirs.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.donki.com/en/"
      },
      "cat": "",
      "lat": 35.6944,
      "lng": 139.7039
    },
    {
      "id": "i-cvQzZnNOWV",
      "day": 5,
      "time": "",
      "name": "```Free Tokyo Wandering```",
      "desc": "```Keep the night intentionally open for spontaneous discoveries and memorable moments.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 35.694,
      "lng": 139.7035
    },
    {
      "id": "i-CmayqPx6tT",
      "day": 6,
      "time": "",
      "name": "```Tsukiji Outer Market```",
      "desc": "```Sample sushi, wagyu skewers, tamagoyaki, and famous Tokyo street food at one of Japan’s legendary food markets.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.tsukiji.or.jp/english/"
      },
      "cat": "",
      "lat": 35.6655,
      "lng": 139.7707
    },
    {
      "id": "i-ui5hHqWIFC",
      "day": 6,
      "time": "",
      "name": "```Guided Asakusa Food & Culture Tour```",
      "desc": "```Explore historic Tokyo with local storytelling, hidden alleys, and traditional food culture.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.getyourguide.com/tokyo-l193/asakusa-cultural-walking-food-tour-t450345/"
      },
      "cat": "",
      "lat": 35.7148,
      "lng": 139.7967
    },
    {
      "id": "i-a1qlx4v9I7",
      "day": 6,
      "time": "",
      "name": "```Senso-ji Temple```",
      "desc": "```Tokyo’s oldest and most famous Buddhist temple sits at the heart of historic Asakusa and offers one of the city’s most iconic traditional experiences. Enter through the massive Kaminarimon Gate beneath its giant red lantern before wandering incense-filled temple grounds surrounded by colorful pagodas, fortune stalls, prayer rituals, and centuries of history. Despite the crowds, the atmosphere remains deeply atmospheric and beautifully connected to old Edo-era Tokyo.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.senso-ji.jp/english/"
      },
      "cat": "",
      "lat": 35.7148,
      "lng": 139.7967
    },
    {
      "id": "i-1KpEwmULDZ",
      "day": 6,
      "time": "",
      "name": "```Nakamise Street```",
      "desc": "```Browse traditional snack stalls and souvenir shops leading toward Senso-ji Temple.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/spot/15/index.html"
      },
      "cat": "",
      "lat": 35.7128,
      "lng": 139.796
    },
    {
      "id": "i-hUeZsz7uRa",
      "day": 6,
      "time": "",
      "name": "```Akihabara```",
      "desc": "```Akihabara is Tokyo’s legendary electric town where anime culture, retro gaming, giant arcades, collectible figures, capsule toy shops, electronics stores, and glowing neon signage combine into sensory overload in the best possible way. Multi-story gaming centers blast music into the streets while anime stores, manga shops, themed cafés, and endless gachapon machines create one of the most uniquely Japanese urban experiences anywhere in the world.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/destinations/eastern-tokyo/akihabara/index.html"
      },
      "cat": "",
      "lat": 35.7022,
      "lng": 139.7745
    },
    {
      "id": "i-mhN62Sexuc",
      "day": 6,
      "time": "",
      "name": "```Retro Arcades in Akihabara```",
      "desc": "```Explore multi-floor gaming arcades packed with rhythm games, claw machines, and retro classics.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/tokyo/things-to-do/best-game-centres-in-tokyo"
      },
      "cat": "",
      "lat": 35.7025,
      "lng": 139.7732
    },
    {
      "id": "i-9XZjHmqeyQ",
      "day": 6,
      "time": "",
      "name": "```Capsule Toy Megastores```",
      "desc": "```Browse giant gachapon stores filled with collectible capsule toys.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://livejapan.com/en/article-a0005044/"
      },
      "cat": "",
      "lat": 35.7018,
      "lng": 139.7732
    },
    {
      "id": "i-1VyIcr1d3I",
      "day": 6,
      "time": "",
      "name": "```Gachapon Department Store```",
      "desc": "```Experience Japan’s massive capsule toy culture with thousands of machines under one roof.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://bandainamco-am.co.jp/others/gashapon-bandai-officialshop/"
      },
      "cat": "",
      "lat": 35.7028,
      "lng": 139.7745
    },
    {
      "id": "i-mmKmNqwC-_",
      "day": 7,
      "time": "",
      "name": "```Sumo Stable Practice```",
      "desc": "```Watch authentic sumo wrestlers train during an intimate morning practice session.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.getyourguide.com/tokyo-l193/tokyo-sumo-morning-practice-tour-t245223/"
      },
      "cat": "",
      "lat": 35.6975,
      "lng": 139.7935
    },
    {
      "id": "i-rdusEXGcOp",
      "day": 7,
      "time": "",
      "name": "```Shimokitazawa Exploration```",
      "desc": "```Wander Tokyo’s coolest indie neighborhood filled with vintage fashion, cafés, vinyl shops, and creative culture.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.gotokyo.org/en/destinations/western-tokyo/shimokitazawa/index.html"
      },
      "cat": "",
      "lat": 35.6614,
      "lng": 139.6677
    },
    {
      "id": "i-hvc20BWnsy",
      "day": 7,
      "time": "",
      "name": "```Vintage Shopping```",
      "desc": "```Explore Tokyo’s famous secondhand fashion and collectible stores.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://tokyocheapo.com/shopping-2/vintage-shopping-shimokitazawa/"
      },
      "cat": "",
      "lat": 35.6618,
      "lng": 139.6675
    },
    {
      "id": "i-f1qnnpVo6D",
      "day": 7,
      "time": "",
      "name": "```Indie Cafés```",
      "desc": "```Relax in cozy hidden cafés scattered throughout Shimokitazawa.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/tokyo/restaurants/best-cafes-in-shimokitazawa"
      },
      "cat": "",
      "lat": 35.661,
      "lng": 139.6672
    },
    {
      "id": "i-eZdWpycC8l",
      "day": 7,
      "time": "",
      "name": "```Vinyl Record Stores```",
      "desc": "```Browse iconic Japanese record shops filled with rare vinyl and music memorabilia.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://tokyocheapo.com/shopping-2/best-record-stores-in-tokyo/"
      },
      "cat": "",
      "lat": 35.6615,
      "lng": 139.6678
    },
    {
      "id": "i-903AacUi0O",
      "day": 7,
      "time": "",
      "name": "```Final Tokyo Dinner```",
      "desc": "```Celebrate your final evening in Tokyo before heading to Hakone.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 35.6918,
      "lng": 139.7044
    },
    {
      "id": "i-At9VjPoAap",
      "day": 8,
      "time": "",
      "name": "```Romancecar / Hakone Transit```",
      "desc": "```Leave Tokyo behind and journey toward Hakone’s mountain landscapes.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.odakyu.jp/english/romancecar/"
      },
      "cat": "",
      "lat": 35.6909,
      "lng": 139.7006
    },
    {
      "id": "i-Z1jAHI4xLc",
      "day": 8,
      "time": "",
      "name": "```Hakone Kowakien Ten-yu Check-In```",
      "desc": "```Arrive at one of Hakone’s most luxurious modern ryokan resorts where traditional Japanese hospitality meets stunning mountain scenery. Spacious rooms, elegant interiors, incredible service, and expansive open-air onsen baths overlooking forested hills create the perfect transition away from Tokyo’s nonstop energy. The property is designed entirely around relaxation, quiet atmosphere, and immersion in Hakone’s famous hot spring culture.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.ten-yu.com/en/"
      },
      "cat": "",
      "lat": 35.2473,
      "lng": 139.0306
    },
    {
      "id": "i-M4CkHMmzf3",
      "day": 8,
      "time": "",
      "name": "```Onsen Experience```",
      "desc": "```Relax in traditional Japanese hot spring baths overlooking Hakone’s mountains.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.japan-guide.com/e/e2292.html"
      },
      "cat": "",
      "lat": 35.2473,
      "lng": 139.0306
    },
    {
      "id": "i-bgvqONpQot",
      "day": 8,
      "time": "",
      "name": "```Kaiseki Dinner```",
      "desc": "```Enjoy a beautifully prepared multi-course Japanese seasonal dinner experience.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.japan-guide.com/e/e2043.html"
      },
      "cat": "",
      "lat": 35.2473,
      "lng": 139.0306
    },
    {
      "id": "i-zWzNBUlv63",
      "day": 9,
      "time": "",
      "name": "```Ryokan Breakfast```",
      "desc": "```Experience a traditional Japanese ryokan breakfast.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 35.2473,
      "lng": 139.0306
    },
    {
      "id": "i-Or1-Hn9Dqu",
      "day": 9,
      "time": "",
      "name": "```Hakone Tea House Experience```",
      "desc": "```Slow down with matcha tea and wagashi sweets in a peaceful Hakone tea house or garden setting.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.hakone.or.jp/5580"
      },
      "cat": "",
      "lat": 35.238,
      "lng": 139.027
    },
    {
      "id": "i--BrGN810dN",
      "day": 9,
      "time": "",
      "name": "```Hakone Shrine```",
      "desc": "```Nestled beside Lake Ashi beneath towering cedar trees, Hakone Shrine is one of Japan’s most atmospheric spiritual sites. Moss-covered stone steps, ancient forest pathways, and the iconic red torii gate rising from the lake create an incredibly peaceful setting surrounded by mountain scenery. The shrine perfectly captures the quieter, mystical side of Japan and feels especially beautiful in Hakone’s cool mountain air.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.hakoneshrine.or.jp/english/"
      },
      "cat": "",
      "lat": 35.2049,
      "lng": 139.025
    },
    {
      "id": "i-kyPAyNrhdj",
      "day": 9,
      "time": "",
      "name": "```Lake Ashi Cruise```",
      "desc": "```Cruise across scenic Lake Ashi with possible Mount Fuji views.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.hakone-kankosen.co.jp/foreign/en/"
      },
      "cat": "",
      "lat": 35.2046,
      "lng": 139.0252
    },
    {
      "id": "i-h_DRVYAR8-",
      "day": 9,
      "time": "",
      "name": "```Hakone Ropeway```",
      "desc": "```Float above volcanic valleys and steaming sulfur vents.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.hakoneropeway.co.jp/foreign/en/"
      },
      "cat": "",
      "lat": 35.2412,
      "lng": 139.0186
    },
    {
      "id": "i-L389J1yA-Y",
      "day": 9,
      "time": "",
      "name": "```Owakudani```",
      "desc": "```Explore Hakone’s volcanic valley famous for black eggs and geothermal activity.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.japan-guide.com/e/e5202.html"
      },
      "cat": "",
      "lat": 35.2412,
      "lng": 139.0186
    },
    {
      "id": "i-pvwFLIrOXf",
      "day": 9,
      "time": "",
      "name": "```Hakone Open-Air Museum```",
      "desc": "```Explore one of Japan’s most beautiful sculpture museums surrounded by mountain scenery.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.hakone-oam.or.jp/en/"
      },
      "cat": "",
      "lat": 35.2462,
      "lng": 139.0489
    },
    {
      "id": "i-hxDbX6ugME",
      "day": 9,
      "time": "",
      "name": "```Onsen Relaxation```",
      "desc": "```Enjoy another peaceful evening soaking in hot springs.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 35.2473,
      "lng": 139.0306
    },
    {
      "id": "i-NgQtEc-w3-",
      "day": 9,
      "time": "",
      "name": "```Ryokan Dinner```",
      "desc": "```Experience another refined Japanese ryokan dining experience.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 35.2473,
      "lng": 139.0306
    },
    {
      "id": "i-TeF5_Wr6Nl",
      "day": 10,
      "time": "",
      "name": "```Final Hakone Morning```",
      "desc": "```Enjoy one last slow morning in the mountains before traveling onward.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 35.2473,
      "lng": 139.0306
    },
    {
      "id": "i-HT1_g6yY82",
      "day": 10,
      "time": "",
      "name": "```Transit to Haneda Airport```",
      "desc": "```Return from Hakone to Tokyo for your evening international flight.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://tokyo-haneda.com/en/"
      },
      "cat": "",
      "lat": 35.5494,
      "lng": 139.7798
    },
    {
      "id": "i-bc6cwFtD_X",
      "day": 10,
      "time": "",
      "name": "```Flight to Seoul```",
      "desc": "```Begin the Korea portion of your adventure.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.koreanair.com/"
      },
      "cat": "",
      "lat": 35.5494,
      "lng": 139.7798
    },
    {
      "id": "i-ct_Tckm16A",
      "day": 11,
      "time": "",
      "name": "```DMZ Tour```",
      "desc": "```Journey to the Korean Demilitarized Zone for one of the trip’s most powerful historical experiences.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.getyourguide.com/seoul-l197/from-seoul-dmz-half-or-full-day-tour-t123456/"
      },
      "cat": "",
      "lat": 37.9586,
      "lng": 126.6779
    },
    {
      "id": "i-UChosLN3vK",
      "day": 11,
      "time": "",
      "name": "```Joint Security Area```",
      "desc": "```View one of the world’s most tense and historic borders.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitkorea.or.kr/"
      },
      "cat": "",
      "lat": 37.9559,
      "lng": 126.6764
    },
    {
      "id": "i-FOrzqLUX6v",
      "day": 11,
      "time": "",
      "name": "```3rd Tunnel```",
      "desc": "```Descend into the underground infiltration tunnel near the North Korean border.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitkorea.or.kr/"
      },
      "cat": "",
      "lat": 37.9362,
      "lng": 126.7011
    },
    {
      "id": "i-3_-eoZBo-N",
      "day": 11,
      "time": "",
      "name": "```Observatory```",
      "desc": "```Peer across the border into North Korea.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitkorea.or.kr/"
      },
      "cat": "",
      "lat": 37.917,
      "lng": 126.68
    },
    {
      "id": "i-RhwFVSMcCU",
      "day": 11,
      "time": "",
      "name": "```Dorasan Station```",
      "desc": "```Visit the symbolic final train station before North Korea.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitkorea.or.kr/"
      },
      "cat": "",
      "lat": 37.8961,
      "lng": 126.6816
    },
    {
      "id": "i-0pRGSqAPjt",
      "day": 11,
      "time": "",
      "name": "```Itaewon Korean BBQ```",
      "desc": "```Celebrate the evening with authentic Korean BBQ in Seoul’s international district.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/seoul/restaurants/best-korean-bbq-restaurants-in-seoul"
      },
      "cat": "",
      "lat": 37.5346,
      "lng": 126.9942
    },
    {
      "id": "i-nlozLYaUEC",
      "day": 12,
      "time": "",
      "name": "```Changdeokgung Palace```",
      "desc": "```Widely considered Seoul’s most beautiful royal palace, Changdeokgung blends elegant Joseon Dynasty architecture with stunning natural surroundings and tranquil courtyards. As a UNESCO World Heritage Site, the palace is celebrated for how harmoniously its buildings integrate with the surrounding landscape. Wandering through ornate throne halls, hidden gates, quiet pathways, and traditional pavilions offers a fascinating glimpse into Korea’s royal past.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://eng.cdg.go.kr/"
      },
      "cat": "",
      "lat": 37.5794,
      "lng": 126.991
    },
    {
      "id": "i--w30LIFn7-",
      "day": 12,
      "time": "",
      "name": "```Secret Garden```",
      "desc": "```Wander tranquil royal gardens hidden behind Changdeokgung Palace.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://eng.cdg.go.kr/"
      },
      "cat": "",
      "lat": 37.581,
      "lng": 126.993
    },
    {
      "id": "i-AX6yo4ZBbN",
      "day": 12,
      "time": "",
      "name": "```Bukchon Hanok Village```",
      "desc": "```Explore preserved traditional Korean homes along scenic hillside streets.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitseoul.net/attractions/Bukchon-Hanok-Village_/378"
      },
      "cat": "",
      "lat": 37.5826,
      "lng": 126.9836
    },
    {
      "id": "i-E7cC_n1hl9",
      "day": 12,
      "time": "",
      "name": "```National Museum of Korea```",
      "desc": "```Discover Korea’s extraordinary history and cultural treasures.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.museum.go.kr/site/eng/home"
      },
      "cat": "",
      "lat": 37.524,
      "lng": 126.9803
    },
    {
      "id": "i-f3e9rBuiFl",
      "day": 12,
      "time": "",
      "name": "```Gwangjang Market```",
      "desc": "```Experience one of Seoul’s most famous traditional food markets.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitseoul.net/markets/Gwangjang-Market_/376"
      },
      "cat": "",
      "lat": 37.5704,
      "lng": 127.0011
    },
    {
      "id": "i-cu_e8v1GG1",
      "day": 12,
      "time": "",
      "name": "```Korean BBQ Dinner```",
      "desc": "```Enjoy another classic Korean dining experience.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/seoul/restaurants/best-korean-bbq-restaurants-in-seoul"
      },
      "cat": "",
      "lat": 37.5703,
      "lng": 127.0008
    },
    {
      "id": "i-ZzrLa--N6R",
      "day": 13,
      "time": "",
      "name": "```Noryangjin Fish Market```",
      "desc": "```Experience Seoul’s legendary seafood market and early morning auctions.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitseoul.net/markets/Noryangjin-Fisheries-Wholesale-Market_/382"
      },
      "cat": "",
      "lat": 37.5128,
      "lng": 126.9408
    },
    {
      "id": "i-DAe2gLQC8u",
      "day": 13,
      "time": "",
      "name": "```Tuna Auction```",
      "desc": "```Watch the excitement of Korea’s famous seafood auction culture.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitseoul.net/"
      },
      "cat": "",
      "lat": 37.5128,
      "lng": 126.9408
    },
    {
      "id": "i-A-36Z5k15a",
      "day": 13,
      "time": "",
      "name": "```Dongdaemun Design Plaza```",
      "desc": "```Explore Seoul’s futuristic architectural landmark and design center.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.ddp.or.kr/?menuno=240"
      },
      "cat": "",
      "lat": 37.5665,
      "lng": 127.0093
    },
    {
      "id": "i-p91rpKI_UF",
      "day": 13,
      "time": "",
      "name": "```COEX Mall```",
      "desc": "```Wander one of Asia’s largest underground malls.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.coex.co.kr/blog/venue/coex-mall/"
      },
      "cat": "",
      "lat": 37.5118,
      "lng": 127.0593
    },
    {
      "id": "i-JoNKJtOYjq",
      "day": 13,
      "time": "",
      "name": "```Starfield Library```",
      "desc": "```Located inside COEX Mall, Starfield Library is one of Seoul’s most visually striking public spaces featuring enormous multi-story bookshelves rising dramatically toward the ceiling beneath modern glass architecture. The space combines bookstore, library, café culture, and social gathering space into one of Seoul’s most photographed modern landmarks and offers a relaxing break from the city’s fast pace.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.starfield.co.kr/coexmall/main/main.do"
      },
      "cat": "",
      "lat": 37.5117,
      "lng": 127.0593
    },
    {
      "id": "i-J9nJjiE1N3",
      "day": 13,
      "time": "",
      "name": "```Seoul Sky```",
      "desc": "```Enjoy panoramic skyline views from one of the tallest buildings in Korea.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://seoulsky.lotteworld.com/en/main/index.do"
      },
      "cat": "",
      "lat": 37.5125,
      "lng": 127.1025
    },
    {
      "id": "i-MNOcr2Kjac",
      "day": 13,
      "time": "",
      "name": "```Gangnam Dinner```",
      "desc": "```Experience Seoul’s modern upscale district made famous worldwide.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitseoul.net/gangnam"
      },
      "cat": "",
      "lat": 37.4979,
      "lng": 127.0276
    },
    {
      "id": "i-VqmSd89Prb",
      "day": 14,
      "time": "",
      "name": "```Namdaemun Market```",
      "desc": "```Explore Korea’s oldest and largest traditional market.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitseoul.net/markets/Namdaemun-Market_/375"
      },
      "cat": "",
      "lat": 37.5588,
      "lng": 126.9777
    },
    {
      "id": "i-Ko78YXp5vQ",
      "day": 14,
      "time": "",
      "name": "```Korean Street Food```",
      "desc": "```Sample iconic Korean snacks and market foods.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/seoul/restaurants/best-street-food-in-seoul"
      },
      "cat": "",
      "lat": 37.559,
      "lng": 126.9777
    },
    {
      "id": "i-ANeqdbRXJP",
      "day": 14,
      "time": "",
      "name": "```N Seoul Tower```",
      "desc": "```Ride above Seoul for incredible city and mountain views.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.nseoultower.co.kr/eng/"
      },
      "cat": "",
      "lat": 37.5512,
      "lng": 126.9882
    },
    {
      "id": "i-LHg7btGl9t",
      "day": 14,
      "time": "",
      "name": "```Namsan Park```",
      "desc": "```Wander scenic walking trails surrounding Seoul’s iconic tower.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitseoul.net/parks/Namsan-Park_/364"
      },
      "cat": "",
      "lat": 37.5497,
      "lng": 126.9876
    },
    {
      "id": "i-aI5jA3xL3S",
      "day": 14,
      "time": "",
      "name": "```Hongdae Exploration```",
      "desc": "```Experience Seoul’s youthful nightlife district filled with live music, cafés, shopping, and performers.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://english.visitseoul.net/hongdae"
      },
      "cat": "",
      "lat": 37.5563,
      "lng": 126.9237
    },
    {
      "id": "i-k_O1ElbDg0",
      "day": 14,
      "time": "",
      "name": "```Live Music & Nightlife```",
      "desc": "```Enjoy Hongdae’s famous creative energy and nightlife atmosphere.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.timeout.com/seoul/music/best-live-music-venues-in-seoul"
      },
      "cat": "",
      "lat": 37.556,
      "lng": 126.924
    },
    {
      "id": "i-f2L0TniNQ8",
      "day": 14,
      "time": "",
      "name": "```Souvenir Shopping```",
      "desc": "```Pick up final gifts, snacks, and souvenirs before returning home.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 37.5563,
      "lng": 126.9237
    },
    {
      "id": "i-qLnartkx9p",
      "day": 15,
      "time": "",
      "name": "```Hotel Checkout```",
      "desc": "```Final departure preparations before heading to the airport.```",
      "url": "```N/A```",
      "cat": "",
      "lat": 37.5546,
      "lng": 126.9224
    },
    {
      "id": "i-DL7o8Yybnw",
      "day": 15,
      "time": "",
      "name": "```Incheon Airport Departure```",
      "desc": "```Depart Korea for your return flight home.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.airport.kr/ap/en/index.do"
      },
      "cat": "",
      "lat": 37.4602,
      "lng": 126.4407
    },
    {
      "id": "i-aoSVhVQBZo",
      "day": 15,
      "time": "",
      "name": "```Return Flight to Seattle```",
      "desc": "```Fly home after an unforgettable Japan and Korea adventure.```",
      "url": {
        "@context": "http://schema.org/",
        "@type": "WebPage",
        "url": "https://www.alaskaair.com/"
      },
      "cat": "",
      "lat": 37.4602,
      "lng": 126.4407
    }
  ],
  "todos": [
    {
      "id": "i-OwODpLyzhJ",
      "priority": "Critical```",
      "item": "```Changdeokgung Secret Garden```",
      "type": "```Tickets```",
      "day": "```Aug 2```",
      "whenToBook": "```NOW```",
      "link": "https://eng.cdg.go.kr/",
      "why": "```Secret Garden requires advance reservation and fills up fast, especially in summer```",
      "rec": "```Book immediately — limited daily entry slots```"
    },
    {
      "id": "i-cQT8XGUQN3",
      "priority": "Critical```",
      "item": "```Hakone Kowakien Ten-yu kaiseki dinner```",
      "type": "```Restaurant```",
      "day": "```July 29```",
      "whenToBook": "```At time of hotel booking```",
      "link": "https://www.ten-yu.com/en/",
      "why": "```Kaiseki dinner at the ryokan is typically pre-arranged as part of your stay package — confirm it's included when you book```",
      "rec": "```Confirm dinner is included in your room plan or add it at booking```"
    },
    {
      "id": "i-MZjRXTuRdb",
      "priority": "Important```",
      "item": "```RURU SHIBUYA```",
      "type": "```Restaurant```",
      "day": "```July 24```",
      "whenToBook": "```Walk-in only, no reservations```",
      "link": "https://maps.app.goo.gl/TosocKzN5RqZwAiQ6",
      "why": "```Only ~15 seats, closes at 8 PM. Queues form quickly on weekends```",
      "rec": "```Arrive close to 11 AM right after teamLab to avoid long waits```"
    },
    {
      "id": "i-IwAhfALqhZ",
      "priority": "Important```",
      "item": "```Onitsuka Tiger Shinjuku South```",
      "type": "```Shopping```",
      "day": "```July 26```",
      "whenToBook": "```Walk-in, no reservation needed```",
      "link": "https://www.onitsukatiger.com/jp/ja-jp",
      "why": "```Can get busy but notably less crowded than Omotesando. Best to go on a weekday or early.```",
      "rec": "```Go early afternoon before evening food tour```"
    },
    {
      "id": "i-nwUmpjokEx",
      "priority": "Important```",
      "item": "```KUOE KYOTO Omotesando```",
      "type": "```Shopping```",
      "day": "```July 25```",
      "whenToBook": "```Walk-in, no reservation needed```",
      "link": "https://linktr.ee/kuoe_kyoto",
      "why": "```Small boutique, closes at 5:30 PM. Closed Tuesdays. July 25 is Saturday so you're fine.```",
      "rec": "```Go before 5:30 PM during Omotesando wandering```"
    },
    {
      "id": "i-W_C8yst36C",
      "priority": "Important```",
      "item": "```Mt. Fuji 5th Station — Fuji Subaru Line road fee```",
      "type": "```Logistics```",
      "day": "```July 31```",
      "whenToBook": "```Pay on the day at the toll gate```",
      "link": "https://www.fujisan-climb.jp/en/",
      "why": "```The Fuji Subaru Line charges a vehicle fee (around 2,000 yen) at the gate. Just have cash or card ready.```",
      "rec": "```No advance booking needed — just pay at the gate on the way```"
    },
    {
      "id": "i-y3MqrmrDLY",
      "priority": "Helpful```",
      "item": "```Coin lockers at Fuji 5th Station for backpacks```",
      "type": "```Logistics```",
      "day": "```July 31```",
      "whenToBook": "```No advance booking```",
      "link": "",
      "why": "```Standard travel backpacks (40–50L) should fit. Have 100-yen coins ready.```",
      "rec": "```Use lockers so you can walk around freely at the summit```"
    },
    {
      "id": "i-heGjfgzEjj",
      "priority": "Helpful```",
      "item": "```Download Google Maps offline — Tokyo, Hakone, Seoul```",
      "type": "```Travel Setup```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "```Google Maps app```",
      "why": "```Japan mobile data is reliable but offline maps are a lifesaver in transit tunnels and rural areas```",
      "rec": "```Download all three regions before you leave home```"
    },
    {
      "id": "i-asKBXXQhie",
      "priority": "Helpful```",
      "item": "```Download Hyperdia or Google Maps for Japan transit```",
      "type": "```Travel Setup```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "https://www.hyperdia.com/en/",
      "why": "```Essential for navigating JR and subway connections```",
      "rec": "```Google Maps works well in Japan for transit — just make sure it's updated```"
    },
    {
      "id": "i-1FlwtfNSVI",
      "priority": "Critical```",
      "item": "```Watch ticktok on mobile app.```",
      "type": "",
      "day": "",
      "whenToBook": "",
      "link": "",
      "why": "",
      "rec": ""
    },
    {
      "id": "i-k2u_F6LU9-",
      "priority": "Critical```",
      "item": "```Register for visit Japan.com```",
      "type": "",
      "day": "",
      "whenToBook": "",
      "link": "",
      "why": "",
      "rec": ""
    },
    {
      "id": "i-R7G7LTEut-",
      "priority": "Critical```",
      "item": "```teamLab Planets TOKYO```",
      "type": "```Tickets```",
      "day": "```July 24```",
      "whenToBook": "```NOW```",
      "link": "https://www.teamlab.art/e/planets/",
      "why": "```Summer slots sell out quickly```",
      "rec": "```Book ASAP```"
    },
    {
      "id": "i-F6Jtonjv7E",
      "priority": "Critical```",
      "item": "```Shibuya Sky```",
      "type": "```Tickets```",
      "day": "```July 24```",
      "whenToBook": "```NOW```",
      "link": "https://www.shibuya-scramble-square.com/sky/",
      "why": "```Sunset/night slots are hardest to get```",
      "rec": "```Prioritize this reservation```"
    },
    {
      "id": "i-V522RR3Cen",
      "priority": "Critical```",
      "item": "```Sumo Stable Practice```",
      "type": "```Tour```",
      "day": "```July 28```",
      "whenToBook": "```NOW```",
      "link": "https://www.getyourguide.com/",
      "why": "```Hardest experience to secure```",
      "rec": "```Book immediately```"
    },
    {
      "id": "i-V7LcbkANHf",
      "priority": "Critical```",
      "item": "```DMZ / JSA Tour```",
      "type": "```Tour```",
      "day": "```Aug 1```",
      "whenToBook": "```NOW```",
      "link": "https://www.getyourguide.com/",
      "why": "```Access changes often```",
      "rec": "```Book highly rated operator```"
    },
    {
      "id": "i-xRmg-qixSD",
      "priority": "Critical```",
      "item": "```Shinjuku night food tour```",
      "type": "```Tour```",
      "day": "```July 26```",
      "whenToBook": "```Next few weeks```",
      "link": "https://www.getyourguide.com/",
      "why": "```Great recovery-day guided experience```",
      "rec": "```Probably your best “insider Tokyo” night```"
    },
    {
      "id": "i-IbEydHNeUF",
      "priority": "Critical```",
      "item": "```Asakusa guided food/culture tour```",
      "type": "```Tour```",
      "day": "```July 27```",
      "whenToBook": "```Next few weeks```",
      "link": "https://www.getyourguide.com/",
      "why": "```Adds huge value to traditional Tokyo```",
      "rec": "```Small-group local guide recommended```"
    },
    {
      "id": "i-dLTH6crVhh",
      "priority": "Critical```",
      "item": "```Sumida River Fireworks Festival viewing strategy```",
      "type": "```Event Planning```",
      "day": "```July 25```",
      "whenToBook": "```NOW```",
      "link": "```https://www.klook.com/ OR https://www.getyourguide.com/```",
      "why": "```Crowds and heat are intense```",
      "rec": "```Consider reserved seating/rooftop```"
    },
    {
      "id": "i-9QxksNLX_z",
      "priority": "Critical```",
      "item": "```Romancecar / Hakone train seats```",
      "type": "```Transit```",
      "day": "```July 29```",
      "whenToBook": "```2–4 weeks before```",
      "link": "https://www.odakyu.jp/english/romancecar/",
      "why": "```Summer seats fill```",
      "rec": "```Reserve family seats together```"
    },
    {
      "id": "i-rhvQdn_7VG",
      "priority": "Important```",
      "item": "```Kura Sushi```",
      "type": "```Restaurant```",
      "day": "```July 26```",
      "whenToBook": "```Morning of or day before```",
      "link": "https://www.kurasushi.co.jp/en/",
      "why": "```Evening waits can get long```",
      "rec": "```Use app or online queue```"
    },
    {
      "id": "i-4NRnsh2daH",
      "priority": "Important```",
      "item": "```FLIPPER'S Shibuya```",
      "type": "```Restaurant```",
      "day": "```July 24```",
      "whenToBook": "```1–2 weeks before```",
      "link": "https://flipper-s.com/",
      "why": "```Morning lines can get long```",
      "rec": "```Reserve if possible```"
    },
    {
      "id": "i-83vb_oI2OP",
      "priority": "Important```",
      "item": "```Pepper PARLOR```",
      "type": "```Restaurant```",
      "day": "```July 24```",
      "whenToBook": "```1–2 weeks before```",
      "link": "https://www.pepperparlor.com/",
      "why": "```Helps keep Shibuya day smooth```",
      "rec": "```Nice-to-have reservation```"
    },
    {
      "id": "i-vNFvdMIxMi",
      "priority": "Important```",
      "item": "```Hedgehog Café HARRY```",
      "type": "```Activity```",
      "day": "```July 25```",
      "whenToBook": "```1–2 weeks before```",
      "link": "https://www.harinezumi-cafe.com/english",
      "why": "```Small capacity```",
      "rec": "```Reserve if convenient```"
    },
    {
      "id": "i-tzUW1RKhDX",
      "priority": "Important```",
      "item": "```Airport limo/private transfer (optional)```",
      "type": "```Transit```",
      "day": "```July 23```",
      "whenToBook": "```1–2 weeks before```",
      "link": "https://webservice.limousinebus.co.jp/web/en/",
      "why": "```Easier after long flight```",
      "rec": "```Optional comfort upgrade```"
    },
    {
      "id": "i-XddZPB8IzE",
      "priority": "Helpful```",
      "item": "```eSIM / Pocket WiFi```",
      "type": "```Travel setup```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "```https://www.airalo.com/ OR https://www.ubigi.com/```",
      "why": "```Essential for navigation/transit```",
      "rec": "```eSIM easiest for family```"
    },
    {
      "id": "i-NwiHq1cJ3v",
      "priority": "Helpful```",
      "item": "```Suica / IC cards setup```",
      "type": "```Transit```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure or airport```",
      "link": "```Apple Wallet / JR East app```",
      "why": "```Makes trains effortless```",
      "rec": "```Add to Apple Wallet```"
    },
    {
      "id": "i-bh_Yduvs5j",
      "priority": "Helpful```",
      "item": "```Portable battery packs```",
      "type": "```Packing```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "```Amazon / Best Buy```",
      "why": "```Phones drain fast in Tokyo heat```",
      "rec": "```Ideally one per person```"
    },
    {
      "id": "i-w6Evl9gxcP",
      "priority": "Helpful```",
      "item": "```Cooling towels / neck fans```",
      "type": "```Packing```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure```",
      "link": "```Amazon```",
      "why": "```Huge comfort upgrade```",
      "rec": "```Especially for fireworks```"
    },
    {
      "id": "i-YiXVjH4XqX",
      "priority": "Helpful```",
      "item": "```UV umbrella/parasol```",
      "type": "```Packing```",
      "day": "```Entire trip```",
      "whenToBook": "```Before departure or buy in Japan```",
      "link": "```Amazon / Don Quijote```",
      "why": "```Makes July heat much easier```",
      "rec": "```You’ll see locals using them everywhere```"
    }
  ],
  "flights": [
    {
      "trip": "```Tokyo → Seoul```",
      "airline": "```Korean Air```",
      "number": "```Korean ```2708```",
      "from": "```HND```",
      "to": "```ICN```",
      "fromCity": "```Tokyo (Haneda)```",
      "toCity": "```Seoul (Incheon)```",
      "date": "2026-07-31",
      "depart": "",
      "arrive": ""
    },
    {
      "trip": "```Seattle → Tokyo```",
      "airline": "```Alaska Airlines```",
      "number": "```Alaska ```823```",
      "from": "```SEA```",
      "to": "```NRT```",
      "fromCity": "```Seattle```",
      "toCity": "```Tokyo (Narita)```",
      "date": "2026-07-22",
      "depart": "",
      "arrive": ""
    },
    {
      "trip": "```Seoul → Seattle```",
      "airline": "```Alaska Airlines```",
      "number": "```Alaska ```172```",
      "from": "```ICN```",
      "to": "```SEA```",
      "fromCity": "```Seoul (Incheon)```",
      "toCity": "```Seattle```",
      "date": "2026-08-05",
      "depart": "",
      "arrive": ""
    }
  ]
};
(function(){
  const D = window.DATA;
  D.byId = {}; D.activities.forEach(a => D.byId[a.id] = a);
  D.byDay = {}; D.days.forEach(d => D.byDay[d.n] = d);
  D.dayActivities = {}; D.activities.forEach(a => {
    (D.dayActivities[a.day] = D.dayActivities[a.day] || []).push(a);
  });
})();
